### ISSUE TITLE
`block in require_program': program version required

### ISSUE THREAD

**Issue by murdoch** [hakirisec/hakiri_toolbelt#1]
I have installed Hakiri V 3.0.0, but I see the following ouput when I run it

**hakiri system:steps**

```
/home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/runner.rb:365:in `block in require_program': program version required (Commander::Runner::CommandError)
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/runner.rb:364:in `each'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/runner.rb:364:in `require_program'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/runner.rb:52:in `run!'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/delegates.rb:7:in `run!'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
/home/stephen/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require': cannot load such file -- http (LoadError)
    from /home/stephen/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/hakiri-0.3.0/lib/hakiri.rb:6:in `<top (required)>'
    from /home/stephen/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /home/stephen/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/gems/hakiri-0.3.0/bin/hakiri:5:in `<top (required)>'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/bin/hakiri:23:in `load'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/bin/hakiri:23:in `<main>'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/stephen/.rvm/gems/ruby-2.0.0-p195@bolster/bin/ruby_noexec_wrapper:14:in `<main>'
```

The gem and all it's dependencies seem to install fine, and I have restarted my CLI

**Comment by seuros** [comment]
Same issue!

**Comment by chahn** [comment]
Same here.

**Comment by krazylegz** [comment]
The missing dependency is http. `gem install http` should resolve this for you.

**Comment by vasinov** [comment]
@murdoch, @seuros, @chahn, @krazylegz, I just fixed it. The http gem is actually not _required_ for Hakiri to work properly but the require statement was still there from some older version. I removed it.

**Comment by murdoch** [comment]
Thankyou @vasinov I can confirm that 0.3.1 does indeed fix this issue.
