### ISSUE TITLE
documentation for using specific version in manifest file is misleading

### ISSUE THREAD

**Issue by mp-jwolkerstorfer** [hakirisec/hakiri_toolbelt#9]
On https://hakiri.io/docs/manifest-file, the code showing a specific version of a technology shows
`"ruby": { "version": "1.9.3.429" }`
but this syntax causes `hakiri system:scan` to fail with

```
/usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/technology.rb:22:in `puts_error': undefined method `lines' for nil:NilClass (NoMethodError)
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/technologies/ruby.rb:13:in `rescue in version'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/technologies/ruby.rb:9:in `version'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/stack.rb:138:in `block in fetch_versions'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/stack.rb:132:in `each'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/stack.rb:132:in `fetch_versions'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/lib/hakiri/cli/system.rb:8:in `scan'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/hakiri-0.7.2/bin/hakiri:34:in `block (2 levels) in <top (required)>'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/delegates.rb:19:in `run!'
from /usr/local/rvm/gems/ruby-1.9.3-p484@mpcp/gems/commander-4.3.0/lib/commander/import.rb:10:in `block in <top (required)>'
```

Instead, the manifest requires the command key to be present, like so:
`"ruby": { "command": "", "version": "1.9.3.429" }`

It will also run correctly with the command specified:
`"ruby": { "command": "ruby --version", "version": "1.9.3.429" }`
This will (correctly, in my opinion) return information about the specified version rather than the version found by the command.

**Comment by vasinov** [comment]
@mp-jwolkerstorfer, does `ruby -v` work on your system?

**Comment by mp-jwolkerstorfer** [comment]
@vasinov Yes, it does.

**Comment by afeld** [comment]
Just ran into this same issue...if the `version` is specified, is there any reason to include/run the `command`?

**Comment by vasinov** [comment]
@afeld do you also use RVM to manage your Rubies? What system are you on?

**Comment by afeld** [comment]
Yes, though my specific issue was that we have a certain version of Portgres on our server, so I specified it explicitly. Hakiri was having trouble accessing postgres in our CI (since it doesn't have access to the 'postgres' server command), so I was surprised when it through an error when it couldn't find the command, even though the version was specified explicitly. Does that make sense?
